export const permissions = {
  READ_MAINTENANCE: "READ_MAINTENANCE",
  UPDATE_MAINTENANCE: "UPDATE_MAINTENANCE",

  READ_MESSAGE: "READ_MESSAGE",
  UPDATE_MESSAGE: "UPDATE_MESSAGE",

  READ_NOTIFICATION: "READ_NOTICE",
  UPDATE_NOTIFICATION: "UPDATE_NOTICE",

  READ_BILL: "READ_BILL",
  UPDATE_BILL: "UPDATE_BILL",

  READ_PROPERTY: "READ_PROPERTY",
  UPDATE_PROPERTY: "UPDATE_PROPERTY",

  READ_TENANT: "READ_TENANT",
  UPDATE_TENANT: "UPDATE_TENANT",

  READ_FINANCE: "READ_FINANCE",
  READ_REPORT: "READ_REPORT",
};
