// export const permissions = [
//   { name: "Create Tenant", value: "CREATE_TENANT" },
//   { name: "Read Tenant", value: "READ_TENANT" },
//   { name: "Update Tenant", value: "UPDATE_TENANT" },
//   { name: "Delete Tenant", value: "DELETE_TENANT" },
//   { name: "Create Property", value: "CREATE_PROPERTY" },
//   { name: "Read Property", value: "READ_PROPERTY" },
//   { name: "Update Property", value: "UPDATE_PROPERTY" },
//   { name: "Delete Property", value: "DELETE_PROPERTY" },
//   { name: "Create Maintainer", value: "CREATE_MAINTAINER" },
//   { name: "Read Maintainer", value: "READ_MAINTAINER" },
//   { name: "Update Maintainer", value: "UPDATE_MAINTAINER" },
//   { name: "Delete Maintainer", value: "DELETE_MAINTAINER" },
//   { name: "Create Manager", value: "CREATE_MANAGER" },
//   { name: "Read Manager", value: "READ_MANAGER" },
//   { name: "Update Manager", value: "UPDATE_MANAGER" },
//   { name: "Delete Manager", value: "DELETE_MANAGER" },
//   { name: "Create Janitor", value: "CREATE_JANITOR" },
//   { name: "Read Janitor", value: "READ_JANITOR" },
//   { name: "Update Janitor", value: "UPDATE_JANITOR" },
//   { name: "Delete Janitor", value: "DELETE_JANITOR" },
//   { name: "Read Maintenance", value: "READ_MAINTENANCE" },
//   { name: "Update Maintenance", value: "UPDATE_MAINTENANCE" },
//   { name: "Delete Maintenance", value: "DELETE_MAINTENANCE" },
//   { name: "Read Finance", value: "READ_FINANCE" },
//   { name: "Read Reports", value: "READ_REPORTS" },
// ];

export const permissions = {
  CREATE_TENANT: "CREATE_TENANT",
  READ_TENANT: "READ_TENANT",
  UPDATE_TENANT: "UPDATE_TENANT",
  DELETE_TENANT: "DELETE_TENANT",
  CREATE_PROPERTY: "CREATE_PROPERTY",
  READ_PROPERTY: "READ_PROPERTY",
  UPDATE_PROPERTY: "UPDATE_PROPERTY",
  DELETE_PROPERTY: "DELETE_PROPERTY",
  CREATE_MAINTAINER: "CREATE_MAINTAINER",
  READ_MAINTAINER: "READ_MAINTAINER",
  UPDATE_MAINTAINER: "UPDATE_MAINTAINER",
  DELETE_MAINTAINER: "DELETE_MAINTAINER",
  CREATE_MANAGER: "CREATE_MANAGER",
  READ_MANAGER: "READ_MANAGER",
  UPDATE_MANAGER: "UPDATE_MANAGER",
  DELETE_MANAGER: "DELETE_MANAGER",
  CREATE_JANITOR: "CREATE_JANITOR",
  READ_JANITOR: "READ_JANITOR",
  UPDATE_JANITOR: "UPDATE_JANITOR",
  DELETE_JANITOR: "DELETE_JANITOR",
  READ_MAINTENANCE: "READ_MAINTENANCE",
  UPDATE_MAINTENANCE: "UPDATE_MAINTENANCE",
  DELETE_MAINTENANCE: "DELETE_MAINTENANCE",
  READ_FINANCE: "READ_FINANCE",
  READ_REPORTS: "READ_REPORTS",
};
